const colors = {
  "primary-container": "#4a675f",
  "surface-dim": "#d8dada",
  surface: "#f8faf9",
  "primary-fixed-dim": "#aecdc3",
  tertiary: "#36503b",
  error: "#ba1a1a",
  "surface-bright": "#f8faf9",
  "surface-container-high": "#e6e9e8",
  "inverse-primary": "#aecdc3",
  "surface-tint": "#47645c",
  "surface-container-highest": "#e1e3e2",
  "on-primary": "#ffffff",
  outline: "#727976",
  "secondary-container": "#c5e4f5",
  "on-primary-container": "#c4e4da",
  "inverse-surface": "#2e3131",
  background: "#f8faf9",
  "tertiary-container": "#4d6851",
  "on-secondary-fixed-variant": "#2d4b58",
  "error-container": "#ffdad6",
  "secondary-fixed": "#c8e7f8",
  "on-surface": "#191c1c",
  "inverse-on-surface": "#eff1f0",
  "surface-container-lowest": "#ffffff",
  "on-primary-fixed": "#02201a",
  "primary-fixed": "#c9e9df",
  "on-tertiary-fixed": "#07200f",
  "on-secondary-container": "#496775",
  "on-surface-variant": "#414846",
  "on-tertiary-fixed-variant": "#334d38",
  primary: "#324f47",
  "surface-variant": "#e1e3e2",
  "surface-container-low": "#f2f4f3",
  "on-error": "#ffffff",
  "outline-variant": "#c1c8c4",
  "on-tertiary-container": "#c7e5c9",
  "on-secondary-fixed": "#001f2a",
  "tertiary-fixed-dim": "#b0ceb2",
  "surface-container": "#eceeed",
  "on-secondary": "#ffffff",
  secondary: "#456271",
  "on-tertiary": "#ffffff",
  "on-error-container": "#93000a",
  "tertiary-fixed": "#cceace",
  "secondary-fixed-dim": "#accbdc",
  "on-primary-fixed-variant": "#304c45",
  "on-background": "#191c1c",
};

module.exports = {
  content: ["./templates/**/*.html", "./src/**/*.rs"],
  darkMode: "class",
  theme: {
    extend: {
      colors,
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "target-min": "48px",
        gutter: "16px",
        unit: "8px",
        "margin-desktop": "24px",
      },
      fontFamily: {
        "title-lg": ["Manrope", "sans-serif"],
        "label-lg": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "label-md": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
      },
      fontWeight: {
        black: "800",
      },
      letterSpacing: {
        tight: "0",
      },
      fontSize: {
        "title-lg": ["22px", { lineHeight: "28px", letterSpacing: "0px", fontWeight: "500" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.1px", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0.25px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.5px", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0.5px", fontWeight: "400" }],
        "display-lg": ["57px", { lineHeight: "64px", letterSpacing: "0px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "0px", fontWeight: "600" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
    require("@tailwindcss/typography"),
  ],
};
