const colorNames = [
  "primary-container",
  "surface-dim",
  "surface",
  "primary-fixed-dim",
  "tertiary",
  "error",
  "surface-bright",
  "surface-container-high",
  "inverse-primary",
  "surface-tint",
  "surface-container-highest",
  "on-primary",
  "outline",
  "secondary-container",
  "on-primary-container",
  "inverse-surface",
  "background",
  "tertiary-container",
  "on-secondary-fixed-variant",
  "error-container",
  "secondary-fixed",
  "on-surface",
  "inverse-on-surface",
  "surface-container-lowest",
  "on-primary-fixed",
  "primary-fixed",
  "on-tertiary-fixed",
  "on-secondary-container",
  "on-surface-variant",
  "on-tertiary-fixed-variant",
  "primary",
  "surface-variant",
  "surface-container-low",
  "on-error",
  "outline-variant",
  "on-tertiary-container",
  "on-secondary-fixed",
  "tertiary-fixed-dim",
  "surface-container",
  "on-secondary",
  "secondary",
  "on-tertiary",
  "on-error-container",
  "tertiary-fixed",
  "secondary-fixed-dim",
  "on-primary-fixed-variant",
  "on-background",
];

const colors = Object.fromEntries(
  colorNames.map((name) => [name, `rgb(var(--color-${name}) / <alpha-value>)`]),
);

module.exports = {
  content: ["./templates/**/*.html", "./src/**/*.rs"],
  darkMode: "class",
  theme: {
    extend: {
      colors,
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "target-min": "48px",
        gutter: "16px",
        unit: "8px",
        "margin-desktop": "24px",
      },
      fontFamily: {
        "title-lg": ["Manrope", "sans-serif"],
        "label-lg": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "label-md": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
      },
      fontWeight: {
        black: "800",
      },
      letterSpacing: {
        tight: "0",
      },
      fontSize: {
        "title-lg": ["22px", { lineHeight: "28px", letterSpacing: "0px", fontWeight: "500" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.1px", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0.25px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.5px", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0.5px", fontWeight: "400" }],
        "display-lg": ["57px", { lineHeight: "64px", letterSpacing: "0px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "0px", fontWeight: "600" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
    require("@tailwindcss/typography"),
  ],
};
